# Site settings
title: Trent Yang
email: trentyang@trentyang.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://trentyang.com" # the base hostname & protocol for your site
github_username:  chun-yang
linkedin_username:  chun-trent-yang-247a8060

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

plugins:
  - jekyll-sitemap
