# Site settings
title: CY Blog
email: cy@charlieyankeeblog.com
description: > # this means to ignore newlines until "baseurl:"
  CY stands for Chun Yang :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://charlieyankeeblog.com" # the base hostname & protocol for your site
github_username:  chun-yang
linkedin_username:  chun-trent-yang-247a8060

# Build settings
markdown: kramdown

theme: jekyll-theme-primer
